# Generated by Django 5.2.9 on 2025-12-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_address', models.CharField(max_length=42, unique=True)),
                ('private_key', models.CharField(max_length=66)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
